import { useEffect,useState } from "react";
import { loadPersonalResults } from "../net/colyseus";
import { EquationText } from "./EquationText";
type Row={objective:string;offered:number;answered:number;firstCorrect:number;firstHint:number;retryCorrect:number;notAttempted:number;interrupted:number;repeated:number;medianResponseSeconds:number|null;responseTimeSamples:number};
type Results={nickname:string;summary:Row[];review:Array<{id:string;objective:string;prompt:string;explanation:string;answer:string;needsPractice:boolean}>};
export function PersonalResults({roomCode}:{roomCode:string}):JSX.Element {
  const [data,setData]=useState<Results|null>(null),[error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();void loadPersonalResults(roomCode,controller.signal).then(value=>setData(value as Results)).catch(error=>{if(!controller.signal.aborted)setError(error.message);});return()=>controller.abort();},[roomCode]);
  return <section className="space-y-3 rounded bg-white p-4"><h3 className="text-xl font-bold">ผลการเรียนรู้ส่วนตัว</h3>{error?<p role="alert">{error}</p>:!data?<p role="status">กำลังอ่านผลของคุณ…</p>:<><p>ผลของ {data.nickname} เท่านั้น · ข้อทบทวนด้านล่างไม่เพิ่มคะแนนหรือจำนวนข้อใหม่</p>{data.summary.map(row=><article key={row.objective} className="rounded border p-3"><h4 className="font-bold">{row.objective}</h4><p>ทำข้อใหม่ {row.answered}/{row.offered} · ถูกครั้งแรก {row.firstCorrect}/{row.answered} · ใช้คำใบ้ {row.firstHint}/{row.answered} · แก้ถูก {row.retryCorrect}/{row.answered}</p><p>ไม่ได้ทำ {row.notAttempted} · ยุติระหว่างทำ {row.interrupted} · ข้อซ้ำ {row.repeated}</p><p>เวลามัธยฐาน {row.medianResponseSeconds?.toFixed(1)??"—"} วินาที จาก {row.responseTimeSamples} คำตอบ — ไม่ใช้ตัดสินความเก่ง</p></article>)}<h4 className="font-bold">ทบทวนข้อที่ได้ทำและวิธีคิด</h4>{data.review.map(question=><details key={question.id} id={`review-${question.id}`} className="rounded border p-3"><summary>{question.needsPractice?"แนะนำให้ฝึก: ":"ทบทวน: "}{question.objective}</summary><EquationText text={question.prompt}/><p>คำตอบ: {question.answer}</p><EquationText text={question.explanation}/></details>)}</>}</section>;
}
