import { useEffect,useState } from "react";
import { parseJsonResponse, genericServerErrorTh } from "./safeJson";
import { apiUrl as api } from "../net/colyseus";
type Summary = { participantId:string; nickname:string; room:string; objective:string; offered:number; answered:number; firstCorrect:number; firstHint:number; retryCorrect:number; wrong:number; notAttempted:number; interrupted:number; repeated:number; medianResponseSeconds:number|null; responseTimeSamples:number; firstAccuracy:number|null };
type Report = { summary:Summary[]; sessions:Array<{ id:string; room_code:string; status:string; finish_reason?:string }>; commonWrongAnswers:Array<{ questionId:string; prompt:string; answer:string; count:number }>; attemptCount:number; disclaimer:string };
export function TeacherReport({ assignmentId }: { assignmentId:string }):JSX.Element {
  const [report,setReport] = useState<Report|null>(null), [error,setError] = useState(""),[revision,setRevision] = useState(0);
  useEffect(()=>{ const controller=new AbortController(); void fetch(`${api}/api/teacher/assignments/${assignmentId}/report`,{ credentials:"include",signal:controller.signal }).then(async(response)=>{ const result=await parseJsonResponse<Report&{error?:string}>(response); if(!response.ok)throw new Error(result?.error??genericServerErrorTh); if(!result)throw new Error(genericServerErrorTh); setReport(result); }).catch((error)=>{if(!controller.signal.aborted)setError(error instanceof Error?error.message:genericServerErrorTh);}); return()=>controller.abort(); },[assignmentId,revision]);
  return <section className="w-full space-y-3 rounded border bg-white p-4"><h3 className="text-xl font-bold">รายงานทักษะจากคำตอบจริง</h3><div className="flex gap-4"><button className="rounded border p-3" onClick={()=>setRevision((value)=>value+1)}>อัปเดตรายงาน</button><a className="rounded border p-3" href={`${api}/api/teacher/assignments/${assignmentId}/report?format=csv`}>ดาวน์โหลด CSV ภาษาไทย</a></div>{error?<p role="alert">{error}</p>:null}
    {report?<><p>{report.disclaimer}</p><p>บันทึกรายคนทั้งหมด {report.attemptCount} รายการ รวมข้อซ้ำ/ข้อยังเปิด จึงอาจมากกว่าจำนวนข้อใหม่</p>
      <div className="overflow-x-auto"><table className="w-full text-left text-sm"><caption className="py-2 text-left">รายคน × ทักษะ — ทุกสัดส่วนแสดงตัวหาร</caption><thead><tr>{["ชื่อเล่น / ห้อง","ทักษะ","ข้อใหม่ที่เสนอ","ตอบครั้งแรกถูก / ที่ทำ","ใบ้ครั้งแรก / ที่ทำ","แก้ถูก","ผิดหลังปิด","ไม่ได้ทำ","ถูกยุติ","ข้อซ้ำ","เวลามัธยฐาน"].map((label)=><th key={label} className="border p-2">{label}</th>)}</tr></thead><tbody>{report.summary.map((row)=><tr key={`${row.participantId}:${row.room}:${row.objective}`}><td className="border p-2">{row.nickname}<br/>{row.room}</td><td className="border p-2">{row.objective}</td><td className="border p-2">{row.offered}</td><td className={`border p-2 ${row.firstAccuracy===null?"bg-slate-100":row.firstAccuracy>=.7?"bg-emerald-100":"bg-amber-100"}`}>{row.firstCorrect}/{row.answered}</td><td className="border p-2">{row.firstHint}/{row.answered}</td><td className="border p-2">{row.retryCorrect}/{row.answered}</td><td className="border p-2">{row.wrong}</td><td className="border p-2">{row.notAttempted}</td><td className="border p-2">{row.interrupted}</td><td className="border p-2">{row.repeated}</td><td className="border p-2">{row.medianResponseSeconds?.toFixed(1)??"—"} s (n={row.responseTimeSamples})</td></tr>)}</tbody></table></div>
      <details><summary>สถานะรายห้อง</summary><ul>{report.sessions.map((room)=><li key={room.id}>{room.room_code} · {room.status} · {room.finish_reason??"ยังไม่จบ"}</li>)}</ul></details>
      <details><summary>คำตอบผิดครั้งแรกที่พบบ่อย (เฉพาะข้อใหม่ ไม่แสดงชื่อผู้ตอบ)</summary><ul className="space-y-2">{report.commonWrongAnswers.map((row)=><li key={`${row.questionId}:${row.answer}`} className="rounded bg-slate-50 p-3">{row.prompt}<br/>คำตอบที่เลือก: {row.answer} · {row.count} ครั้ง</li>)}</ul></details></>:<p role="status">กำลังอ่านรายงาน…</p>}
  </section>;
}
