export const avatarPresets = [
  { id:"girl", label:"นักสำรวจรุ่นเยาว์", role:"student", age:"youth", skin:"#d6a77d", hair:"long", suit:"#e3a650", build:.9 },
  { id:"boy", label:"นักเรียนวัยรุ่น", role:"student", age:"teen", skin:"#8b5b40", hair:"curly", suit:"#4e9caf", build:1 },
  { id:"scientist", label:"นักวิทยาศาสตร์อาวุโส", role:"science", age:"senior", skin:"#ad7650", hair:"short", suit:"#e9ece4", build:1.1 },
  { id:"scientist-young", label:"นักวิทยาศาสตร์", role:"science", age:"adult", skin:"#edc7a5", hair:"long", suit:"#eef3ee", build:.95 },
  { id:"engineer", label:"วิศวกรภาคสนาม", role:"engineer", age:"adult", skin:"#774a34", hair:"short", suit:"#e5a33a", build:1.1 },
  { id:"engineer-wheelchair", label:"วิศวกรออกแบบ · รถเข็น", role:"engineer", age:"adult", skin:"#d39a74", hair:"curly", suit:"#67a6ab", build:1, wheelchair:true },
  { id:"astro", label:"นักบินอวกาศ", role:"space", age:"adult", skin:"#b47a54", hair:"short", suit:"#dae5e9", build:1.1 },
  { id:"astronaut-senior", label:"นักบินอวกาศอาวุโส", role:"space", age:"senior", skin:"#e3b98f", hair:"short", suit:"#e5e0cf", build:1.2 },
  { id:"doctor", label:"แพทย์", role:"health", age:"adult", skin:"#6c4837", hair:"curly", suit:"#dce8e0", build:1 },
  { id:"nurse", label:"พยาบาลอาวุโส", role:"health", age:"senior", skin:"#d1a17d", hair:"long", suit:"#75b5b0", build:1.15 },
  { id:"teacher", label:"ครู", role:"teacher", age:"adult", skin:"#af7750", hair:"long", suit:"#ab8067", build:1 },
  { id:"teacher-senior", label:"ครูอาวุโส", role:"teacher", age:"senior", skin:"#e1ba95", hair:"short", suit:"#8a98a5", build:1.15 },
  { id:"architect", label:"สถาปนิก", role:"architect", age:"adult", skin:"#6e4939", hair:"long", suit:"#8b9a8e", build:1.05 },
  { id:"architect-young", label:"สถาปนิกฝึกงาน", role:"architect", age:"adult", skin:"#e0b087", hair:"curly", suit:"#5f859e", build:.95 },
  { id:"athlete", label:"นักกีฬาวัยรุ่น", role:"athlete", age:"teen", skin:"#a4714e", hair:"short", suit:"#d86748", build:1.15 },
  { id:"athlete-wheelchair", label:"นักกีฬา · รถเข็น", role:"athlete", age:"adult", skin:"#754b39", hair:"long", suit:"#886ba8", build:1.1, wheelchair:true },
  { id:"pilot", label:"นักบิน", role:"pilot", age:"adult", skin:"#d4a17d", hair:"long", suit:"#425e81", build:1 },
  { id:"pilot-senior", label:"นักบินอาวุโส", role:"pilot", age:"senior", skin:"#9b684b", hair:"short", suit:"#536b87", build:1.1 },
  { id:"firefighter", label:"นักดับเพลิง", role:"firefighter", age:"adult", skin:"#694534", hair:"short", suit:"#c59940", build:1.2 },
  { id:"firefighter-trainee", label:"นักดับเพลิงฝึกงาน", role:"firefighter", age:"adult", skin:"#deb38f", hair:"long", suit:"#d99e4e", build:1.05 },
  { id:"artist", label:"ศิลปิน", role:"artist", age:"adult", skin:"#a26946", hair:"curly", suit:"#a86a85", build:1.1 },
  { id:"musician", label:"นักดนตรีอาวุโส", role:"artist", age:"senior", skin:"#edc5a4", hair:"long", suit:"#6b8c9f", build:1 },
  { id:"explorer", label:"นักสำรวจธรรมชาติ", role:"nature", age:"adult", skin:"#ba875e", hair:"short", suit:"#8a9870", build:1.1 },
  { id:"naturalist", label:"นักธรรมชาติวิทยาอาวุโส", role:"nature", age:"senior", skin:"#81583f", hair:"long", suit:"#b4966c", build:1.15 },
] as const;
export function avatarById(id: string) { return avatarPresets.find((preset) => preset.id === id) ?? avatarPresets[0]; }
